# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a78190d873a338945ff6e5c701e7a78ef3e7341041a883aeaa16c3af6d831f2069668ca9cceaac99401d7b1b62a1d5fc8ae00177b19eac3f2c479383e860b7

test:
  secret_key_base: d63b8ec0212527f9635f21f3972a19dba75b23254bea00c4f3ed18c5e6eb362872592bf654852ee8cba3deafa2c6ca6b34e306c0894623ddc43a63e4adb77045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
